# Docker Compose file for pit tool


# Replace: /home/markus/pit_data/build with your local path

# Build with:
# docker-compose build pit

# Run with:
# docker-compose up

version: '3'
services:
  pit_powerpc:
    build:
      context: .
      args:
        - SEL_ARCH=powerpc
        - SEL_CC=/usr/bin/powerpc64-linux-gnu-gcc-6
        - SEL_CXX=/usr/bin/g++-6
    volumes:
      - pit_data:/home/user/build
      - pit_results:/home/user/results
      - ${LINUX_SRC}:/home/user/linux-stable

    ports:
      - "1230:22"

  pit_arm:
    build:
      context: .
      args:
        - SEL_ARCH=arm
        - SEL_CC=/usr/bin/arm-linux-gnueabihf-gcc
        - SEL_CXX=/usr/bin/g++
    volumes:
      - pit_data:/home/user/build
      - pit_results:/home/user/results
      - ${LINUX_SRC}:/home/user/linux-stable

    ports:
      - "1231:22"

  pit_arm64:
    build:
      context: .
      args:
        - SEL_ARCH=arm64
        - SEL_CC=/usr/bin/aarch64-linux-gnu-gcc
        - SEL_CXX=/usr/bin/g++
    volumes:
      - pit_data:/home/user/build
      - pit_results:/home/user/results
      - ${LINUX_SRC}:/home/user/linux-stable
    ports:
      - "1232:22"

  pit_x86:
    build:
      context: .
      args:
        - SEL_ARCH=x86
        - SEL_CC=/usr/bin/gcc
        - SEL_CXX=/usr/bin/g++
    volumes:
      - pit_data:/home/user/build
      - pit_results:/home/user/results
      - ${LINUX_SRC}:/home/user/linux-stable
    ports:
      - "1233:22"
volumes:
  pit_data:
    external: true
  pit_results:
    external: true

